older version

diff --git a/forms-flow-documents/Dockerfile b/forms-flow-documents/Dockerfile
--- a/forms-flow-documents/Dockerfile
+++ b/forms-flow-documents/Dockerfile
@@ -1,64 +1,51 @@
-# Author: Kurian Benoy
+#Author: Kurian Benoy
 FROM python:3.12.6-slim
 
-# Set label for the image
+# set label for image
 LABEL Name="formsflow"
 
-# Set working directory
 WORKDIR /forms-flow-documents/app
 
-# Install necessary dependencies
-RUN apt-get update \
-    && apt-get install -y --no-install-recommends \
-       gnupg2 \
-       curl \
-       wget \
-       unzip \
-       git \
-       ca-certificates \
-       xvfb \
-    && rm -rf /var/lib/apt/lists/*
+# install curl, gnupg2 and unzip
+RUN  apt-get update \
+  && apt-get install -y gnupg2 \
+  && apt-get install -y curl \
+  && apt-get install -y wget \
+  && apt-get install -y unzip \
+  && apt-get install -y git \
+  && rm -rf /var/lib/apt/lists/*
 
-# Set environment variables
-ENV CHROMEDRIVER_VERSION=116.0.5845.96
-ENV CHROMEDRIVER_DIR=/usr/local/bin
-
-# Download and install Chromedriver
-RUN wget -q "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.85/linux64/chromedriver-linux64.zip" \
-    && unzip chromedriver-linux64.zip -d /usr/local \
-    && cp -rf /usr/local/chromedriver-linux64/* /usr/local/bin \
-    && rm chromedriver-linux64.zip \
-    && chmod +x /usr/local/bin/chromedriver
+# Install Chrome WebDriver - version 116.0.5845.96
+RUN mkdir -p /opt/chromedriver && \
+    curl -sS -o /tmp/chromedriver_linux64.zip https://formsflow-documentsapi.aot-technologies.com/chromedriver-linux64.zip && \
+    unzip -qq /tmp/chromedriver_linux64.zip -d /opt/chromedriver && \
+    rm /tmp/chromedriver_linux64.zip && \
+    chmod +x /opt/chromedriver/chromedriver-linux64/chromedriver && \
+    ln -fs /opt/chromedriver/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
 
 # Install Google Chrome
-RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg \
-    && echo "deb [signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
-    && apt-get update \
-    && apt-get install -y --no-install-recommends google-chrome-stable \
-    && rm -rf /var/lib/apt/lists/*
+RUN wget --no-verbose -O /tmp/chrome.deb https://formsflow-documentsapi.aot-technologies.com/google-chrome-stable_116.0.5845.140-1_amd64.deb || (echo "Failed to download Chrome package" && exit 1) && \
+    apt-get update && \
+    apt-get install -y /tmp/chrome.deb || (echo "Failed to install Chrome package" && exit 1) && \
+    rm /tmp/chrome.deb
 
-# Set display port to avoid crash
+
+
+
+# set display port to avoid crash
 ENV DISPLAY=:99
 
-# Install Python dependencies
 COPY requirements.txt .
 ENV PATH=/venv/bin:$PATH
 
-RUN python3 -m venv /venv \
-    && /venv/bin/pip install --upgrade pip \
-    && /venv/bin/pip install -r requirements.txt
+RUN : \
+    && python3 -m venv /venv \
+    && pip install --upgrade pip \
+    && pip install -r requirements.txt 
 
-# Add application code
 ADD . /forms-flow-documents/app
+RUN pip install -e .
 
-# Install the application in editable mode
-RUN /venv/bin/pip install -e .
-
-# Expose application port
 EXPOSE 5006
-
-# Make the entrypoint script executable
-RUN chmod +x ./entrypoint
-
-# Set entrypoint
+RUN chmod u+x ./entrypoint
 ENTRYPOINT ["/bin/sh", "entrypoint"]
