FWF-4286: Updated GitHub Actions for forms-flow-bpm and web workflows to handle urls dynamically

diff --git a/.github/workflows/forms-flow-bpm-cd.yml b/.github/workflows/forms-flow-bpm-cd.yml
--- a/.github/workflows/forms-flow-bpm-cd.yml
+++ b/.github/workflows/forms-flow-bpm-cd.yml
@@ -12,7 +12,7 @@ defaults:
   run:
     shell: bash
     working-directory: ./forms-flow-bpm
-    
+
 jobs:
   build-and-push-image-to-dockerhub:
     if: github.repository == 'AOT-Technologies/forms-flow-ai'
@@ -63,7 +63,9 @@ jobs:
       - name: Log in to the Container registry
         uses: docker/login-action@v1
         with:
+
           # registry: ${{ env.REGISTRY }}
+
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
 
@@ -94,6 +96,7 @@ jobs:
           file: forms-flow-bpm/Dockerfile
           tags: ${{ steps.meta.outputs.tags }}, formsflow/forms-flow-bpm:latest
           labels: ${{ steps.meta.outputs.labels }}
+
       # - name: Build and push Docker image - arm64
       #   uses: docker/build-push-action@v4
       #   with:
@@ -103,6 +106,8 @@ jobs:
       #     platforms: linux/arm64/v8
       #     tags: ${{ steps.meta.outputs.tags }}-arm64
       #     labels: ${{ steps.meta.outputs.labels }}
+
+      
       - name: Scan Docker image 🐳
         uses: snyk/actions/docker@master
         continue-on-error: true
@@ -116,20 +121,23 @@ jobs:
         uses: github/codeql-action/upload-sarif@v2
         with:
           sarif_file: snyk.sarif
-#####
+
       - name: Set up AWS CLI
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_DEPLOYMENT_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_DEPLOYMENT_SECRET_ACCESS_KEY }}
           aws-region: ca-central-1  # Change this to your desired region
+
       - name: Install kubectl
         run: |
           curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
           chmod +x kubectl
           sudo mv kubectl /usr/local/bin/
+
       - name: Update Kube config
         run: aws eks update-kubeconfig --region ca-central-1 --name ${{ secrets.DEV_EKS_CLUSTER }}
+
       - name: Deploy to eks
         run: |
           kubectl -n ${{ secrets.DEV_OPENSOURCE_NAMESPACE }} patch deployment forms-flow-bpm -p '{"spec":{"template":{"spec":{"containers":[{"name":"forms-flow-bpm","image":"docker.io/formsflow/forms-flow-bpm:${{ env.VERSION }}"}]}}}}'
@@ -139,18 +147,45 @@ jobs:
     runs-on: ubuntu-latest
     name: Scan the application
     steps:
-      - name: Checkout
+      - name: Checkout repository
         uses: actions/checkout@v2
         with:
           ref: master
-      
+
+      - name: Check which URL is up
+        id: check-urls
+        run: |
+          DEV_URL="${{ secrets.BPM_DEV_URL }}"
+          QA_URL="${{ secrets.BPM_QA_URL }}"
+        
+          # Check DEV
+          echo "Checking DEV URL..."
+          RESPONSE_DEV=$(curl -s -o /dev/null -w "%{http_code}" "$DEV_URL" || echo "Failed")
+          if [ "$RESPONSE_DEV" -eq 200 ]; then
+            echo "DEV URL is up"
+            echo "BPM_TARGET_URL=dev" >> $GITHUB_ENV
+          else
+            echo "DEV URL is down"
+            # Check QA only if DEV is down
+            RESPONSE_QA=$(curl -s -o /dev/null -w "%{http_code}" "$QA_URL" || echo "Failed")
+            if [ "$RESPONSE_QA" -eq 200 ]; then
+              echo "QA URL is up"
+              echo "BPM_TARGET_URL=qa" >> $GITHUB_ENV
+            else
+              echo "Both DEV and QA URLs are down"
+              exit 1
+            fi
+          fi
+
+      - name: Print selected target
+        run: |
+          echo "Selected target is: ${{ env.BPM_TARGET_URL }}"
+
       - name: ZAP Scan
         uses: zaproxy/action-full-scan@v0.8.0
         with:
-          working-directory: zap-reports
           token: ${{ secrets.GITHUB_TOKEN }}
-          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
-          target: ${{ secrets.BPM_TARGET_URL }}
+          target: ${{ env.BPM_TARGET_URL }}
           rules_file_name: '.zap/rules.tsv'
 
       - name: Install AWS CLI
